// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvtUAzZXNotU-VvcW06jorjPABX2dyJjg',
    appId: '1:443281339548:web:4363afd4431baed2316959',
    messagingSenderId: '443281339548',
    projectId: 'spotify-e3310',
    authDomain: 'spotify-e3310.firebaseapp.com',
    storageBucket: 'spotify-e3310.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNaPBPTGHyZS1nFV27alz6pS7deMDefqs',
    appId: '1:443281339548:android:4199e079b2887361316959',
    messagingSenderId: '443281339548',
    projectId: 'spotify-e3310',
    storageBucket: 'spotify-e3310.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxm7QbCVT1Z20Qv2a1BLkJlYZ9Aa1lIok',
    appId: '1:443281339548:ios:4934732761f85207316959',
    messagingSenderId: '443281339548',
    projectId: 'spotify-e3310',
    storageBucket: 'spotify-e3310.appspot.com',
    iosBundleId: 'com.example.flutterSpotifyUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxm7QbCVT1Z20Qv2a1BLkJlYZ9Aa1lIok',
    appId: '1:443281339548:ios:87babcc8673855af316959',
    messagingSenderId: '443281339548',
    projectId: 'spotify-e3310',
    storageBucket: 'spotify-e3310.appspot.com',
    iosBundleId: 'com.example.flutterSpotifyUi.RunnerTests',
  );
}
